name: Build on Ubuntu

on: [push, pull_request]

jobs:
  build:
    name: With USE_UPNP=${{ matrix.with_upnp }}
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        with_upnp: ['yes', 'no']
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install build-essential libboost1.74-dev libminiupnpc-dev libssl-dev zlib1g-dev
    - name: build application
      run: make USE_UPNP=${{ matrix.with_upnp }} -j3
