name: Build on FreeBSD

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    name: with UPnP
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        mem: 2048
        prepare: pkg install -y devel/cmake devel/gmake devel/boost-libs security/openssl net/miniupnpc 
        run: |
          cd build
          cmake -DWITH_UPNP=ON -DCMAKE_BUILD_TYPE=Release .
          gmake -j2
