name: Build on OSX

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-osx.yml
    - daemon/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Makefile
    - Makefile.homebrew
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: With USE_UPNP=${{ matrix.with_upnp }}
    runs-on: macOS-latest

    strategy:
      fail-fast: true
      matrix:
        with_upnp: ['yes', 'no']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install required formulae
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        brew update
        brew install boost miniupnpc openssl@1.1

    - name: List installed formulae
      run: brew list

    - name: Build application
      run: make HOMEBREW=1 USE_UPNP=${{ matrix.with_upnp }} PREFIX=$GITHUB_WORKSPACE/output -j3
